config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  resources :events do
    resources :comments
  end
  resources :users
  get 'users/index'
  #get 'home/index'
  get 'home/about'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	def self.search_by(search_term)
		where("LOWER(event_name) LIKE :search_term OR LOWER(event_description) LIKE :search_term OR LOWER(city) LIKE :search_term OR cast(start_date as text) LIKE :search_term OR cast(end_date as text) LIKE :search_term ",search_term: "%#{search_term.downcase}%")
	end
	def self.event_name(event_name)
		where("LOWER(event_name) LIKE :event_name",event_name: "%#{event_name.downcase}%")
	end
	def self.event_description(event_description)
		where("LOWER(event_description) LIKE :event_description",event_description: "%#{event_description.downcase}%")
	end
	def self.start_date(start_date)
		where("start_date LIKE :start_date",start_date: "%#{start_date.downcase}%")
	end
	def self.end_date(end_date)
		where("end_date LIKE :end_date",end_date: "%#{end_date.downcase}%")
	end
	def self.city(city)
		where("LOWER(city) LIKE :city",city: "%#{city.downcase}%")
	end
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :users, through: :comments
	mount_uploader :image, ImageUploader
	validates :image, file_size: {less_than: 5.megabytes}
	validate :end_date_after_start_date?

	scope :expired_events, -> { where('end_date < ?', Date.current) }
	after_save_commit :delete_expired_events


	def delete_expired_events
		DeleteExpiredEventsJob.perform_later

	end

	def end_date_after_start_date?
		if end_date < start_date
			errors.add :end_date, "must be after start date"
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :events, dependent: :destroy
         has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	
	

	before_action :configure_permitted_parameters, :if => :devise_controller?

	protected

	def configure_permitted_parameters
	   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :username, :phone_no, :role , :email, :password, :remember_me) }
	   devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
	   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :username, :phone_no, :role , :email, :password, :current_password,:remember_me) }
		
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController




  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(comment_params)

    if @comment.save
      UserMailer.signup_email(@event.id).deliver_later
      redirect_to @event
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @comment = Comment.find(params[:id])




  end

  def update
    @event = Event.find(params[:event_id])
    @comment = Comment.find(params[:id])

      if @comment.update(comment_params)
        flash[:notice] = "Comment was successfully edited"
        redirect_to @event
      else
        render 'edit'

      end
  end



  def destroy
    @event = Event.find(params[:event_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to @event
  end


  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /events or /events.json
  def index

    @events=Event.all
    if params[:event_name]
      @event_name = params[:event_name]
      @events = @events.event_name(@event_name)
    end

    if params[:event_description]
      @event_description = params[:event_description]
      @events = @events.event_description(@event_description)
    end

    if params[:city]
      @city = params[:city]
      @events = @events.city(@city)
    end


    @events=@events.start_date(params[:start_date]) if params[:start_date].present?
    @events=@events.end_date(params[:end_date]) if params[:end_date].present?

    if params[:search]
      @search_term = params[:search]
      @events = @events.search_by(@search_term)



    end



  end



  # GET /events/1 or /events/1.json
  def show
    @events = Event.find(params[:id])
    @comment = Comment.new
    @comments = @event.comments

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Event PDF",
               template: "events/show.html.erb",
               layout: 'pdf.html'

      end
    end



  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    if current_user != @event.user and !current_user.admin?
    @event = current_user.events.find_by(id: params[:id])
    redirect_to events_path, notice: "Not Authorized" if @event.nil?
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:event_name, :event_description, :start_date, :end_date, :city, :latitude, :longitude, :image, :remove_image, :image_cache, :street_address,:city1,:state,:country,:zip_code)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  	@events = Event.all
  	
  	
  end
  def show
  	@user = User.find(params[:id])
  	@user_events = @user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
 <% @comments.each do |c| %>
   <hr>
   <j>
     <%= c.comment %>
   - Commented by <%= c.user.name %>
     <% if user_signed_in? && (current_user == @event.user || current_user.admin?) %>
     <%= link_to "Delete", event_comment_path(c.event_id,c.id), method: :delete ,class:"btn btn-danger"  %>
       <%= link_to "Edit", edit_event_comment_path(c.event_id,c.id),class:"btn btn-primary"  %>
   </j>
       <% end %>

 <% end %>

app/views/comments/_form.html.erb
<%= form_for ([@event, @comment]) do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :comment,class:"form-control" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  </br>
  <%= f.submit "Add a Comment" ,class:'btn btn-primary' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit the Comment</h1>
<%= render 'comments/form' %>

app/views/events/_errors.html.erb
<% if event.errors.any? %>
  <ul class="list-group">
    <% event.errors.full_messages.each do |message| %>
      <li class="list-group-item list-group-item-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/events/_form.html.erb
<div class="card" style="width: 50rem;">
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= javascript_pack_tag "events", "data-turbolinks-track" => true %>
  <%= javascript_pack_tag "auto-complete", "data-turbolinks-track" => true %>
    <div class="card-body">
  <div class="field form-group">
    <%= form.label :event_name %>
    <%= form.text_field :event_name,class:"form-control" %>
  </div></br>

  <div class="field form-group">
    <%= form.label :event_description %>
    <%= form.text_area :event_description,class:"form-control" %>
  </div></br>

  <div class="field form-group">
    <%= form.label :start_date %>
    <%= form.text_field :start_date,class:"form-control",id:"datepicker" %>
  </div></br>

  <div class="field form-group">
    <%= form.label :end_date %>
    <%= form.text_field :end_date,class:"form-control",id:"datepicker1" %>
  </div></br>

  <div class="field form-group">
    <%= form.label :city , "Address" %>
    <%= form.text_field :city1,class:"form-control" , id:"autocomplete", onFocus:"geolocate()", placeholder: "Enter Address to fill the form" %>
  </div></br>

  <div class="field form-group">
    <%= form.hidden_field :latitude,class:"form-control" , id:"loc_lat" %>
  </div>

  <div class="field form-group">
    <%= form.hidden_field :longitude,class:"form-control", id:"loc_long" %>
  </div>

  <div class="field form-group">
    <%= form.label "Street Address" %>
    <%= form.text_field :street_address,class:"form-control" , id:"street_number" %>
  </div></br>

  <div class="field form-group">
    <%= form.label "City" %>
    <%= form.text_field :city,class:"form-control" , id:"locality" %>
  </div></br>

  <div class="field form-group">
    <%= form.label "State" %>
    <%= form.text_field :state,class:"form-control" , id:"administrative_area_level_1" %>
  </div></br>

  <div class="field form-group">
    <%= form.label "Country" %>
    <%= form.text_field :country,class:"form-control" , id:"country" %>
  </div></br>

  <div class="field form-group">
    <%= form.label "Zip Code" %>
    <%= form.text_field :zip_code,class:"form-control" , id:"postal_code" %>
  </div></br>

  <% if event.image? %>
    <div class="image_wrapper">
      <%= image_tag event.image.thumb.url %>
    </div>
    <% end %>

  <div class="field form-group">
    <%= form.label "Upload an Image to Event" %>
    <%= form.file_field :image, class:"form-control"%>
  </div>
  <% if event.image? %>
    <div class="form-check">
      <label class="form-check-label">
        <%= form.check_box :remove_image, class:"form-check-input" %> Remove Image
      </label>
    </div>
      <% end %></br>



  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

<%= render 'errors', event: event %>
</div>
</div>

app/views/events/edit.html.erb
<div class="card-header" style="width: 50rem;">
<h1>Editing Event</h1>
</div>

<%= render 'form', event: @event %>

 </br>
<%= link_to 'Back', events_path,class:"btn btn-primary" %>

app/views/events/index.html.erb
<h1>Events List</h1>
<%= javascript_pack_tag "events", "data-turbolinks-track" => true %>
<div class="row">
  <div class="col">
<%=  form_tag events_path, :method => 'get' do %>
  <%= label_tag :event_name, "Name:" %>
      <%= text_field_tag :event_name,@event_name,class:"form-control",  placeholder: "Enter Event Name to search",id:"tags" %></div>
    <div class="col">
    <%= label_tag :event_description, "Description:" %>
      <%= text_field_tag :event_description,@event_description,class:"form-control", placeholder:"Enter Event Description to search" %></div>
     <div class="col">
    <%= label_tag :start_date, "Select Start Date to search: " %>
       <%= date_field_tag :start_date,@start_date,class:"form-control" %></div>

    <div class="col">
    <%= label_tag :end_date, "Select End Date to search: " %>
      <%= date_field_tag :end_date,@end_date,class:"form-control" %></div>
    <div class="col">
    <%= label_tag :city, "City:" %>
      <%= text_field_tag :city,@city,class:"form-control",placeholder:"Enter City to search" %></div>
    <div class="col">
      <span style="padding-bottom: 10px;"><%= submit_tag "Search",class:"btn btn-primary" %></span>
      <span style="padding-left:1px;"><%= link_to 'Reset', events_path,class:"btn btn-primary" %></span></div>


  <% end %>




</div>
</br>

<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Event name</th>
      <th>Event description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>City</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>

    <% @events.each do |event| %>
    
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_description %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.city %></td>
        <td><%= event.user.name if event.user %></td>

        <td><%= link_to 'Show', event,class:"btn btn-primary" %></td>

        <% if user_signed_in? && (current_user == event.user || current_user.admin?) %>

        
        <td><%= link_to 'Edit', edit_event_path(event),class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path,class:"btn btn-secondary" %>

app/views/events/new.html.erb
<div class="card-header" style="width: 50rem;">
<h1>New Event</h1>
</div>

<%= render 'form', event: @event %></br>

<%= link_to 'Back', events_path,class:"btn btn-primary" %>

app/views/events/show.html.erb
<div class="jumbotron">
  <% unless request.format.to_sym == :pdf %>
 <pre>                                                                                                                              <%= link_to 'Create a PDF document of this page', event_path(@event, format: :pdf),class:"btn btn-primary" %></pre>
<% end %>
    <h1 class="display-4"></h1>
<p class="lead">
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>
<hr class="my-4">
<p>
  <strong>Event description:</strong>
  <%= @event.event_description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>
  <% if @event.image.url %>
  <p>
    <strong>Image:</strong>
    <% if @event.image %>
    <div class="image_wrapper">
      <%= image_tag(@event.image.url,alt: 'Image') if @event.image.url %>
    </div>
    <% end %>
  </p>
    <% end %>
<hr>
  <%= render 'comments/form' %>
  <%= render 'comments/comment' %>

<% if user_signed_in? && (current_user == @event.user || current_user.admin?) %>
<p class="lead"></br>
<%= link_to 'Edit', edit_event_path(@event),class:"btn btn-primary" %> |

<% end %>
<%= link_to 'Back', events_path,class:"btn btn-primary" %>
</p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Event Application', root_path, class:"navbar-brand", id: "logo" %>
  <div class="container-fluid">
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link active" %>
          
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link active" %>
          
        </li>
        
        <li class="nav-item">
          <%= link_to 'Events', events_path, class:"nav-link active" %>
          
        </li>
        <% if user_signed_in? %>
        
        <li class="nav-item">
          <%= link_to 'Edit User', edit_user_registration_path, class:"nav-link active" %>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link active" %>
          
        </li>

        <% else %>
        
        <li class="nav-item">
          <%= link_to 'Users', users_path, class:"nav-link active" %>
          
        </li>

       <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link active" %>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
          
        </li>

        <% end %>

      </ul>

      <%=  form_tag events_path, :method => 'get' do %>
        <%= text_field_tag :search, @search_term,placeholder: "Search",class:"form-control" %></br>
          <%= submit_tag "Search" ,class:"btn btn-light"%>
        <span style="padding-left:10px;"><%= link_to 'Reset', events_path,class:"btn btn-light" %></span>
      <% end %>


    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> This Application is Created by Me! (Pradeepan Mohan) :-) </h1>

app/views/home/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3" , id="jumbo">

  <% if user_signed_in? %>
    <h1>Welcome to Event Application</h1></br>
    <% else %>
    <h1>Welcome to Event Application</h1></br>
    <h2>Sign up or Sign In to create event!</h2></br>

  <h4><%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary" %></h4>
  or
  <h4><%= link_to 'Sign In', new_user_session_path, class:"btn btn-primary" %></h4>
</div>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright © <a href="https://twitter.com/pradeep00271">Check out my Twitter!</a>
      and Linked In Profile  <a href="https://www.linkedin.com/in/pradeepan-m-0b0851168/">Pradeepan Mohan</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", home_about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgvGb3-JG1qPLibHyBT5ijvjiNZX-zbFc&libraries=places&callback=initAutocomplete" async defer></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Event Application</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container"></br>
        <% if notice %>
        <%= render 'layouts/alerts' %>
        <% end %>
    </br>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
  <%= wicked_pdf_stylesheet_link_tag "events" -%>
  <%= wicked_pdf_stylesheet_link_tag "comments" -%>
  <%= wicked_pdf_stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" %>

</head>
<body>
<div class='container'>
  <%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
<h1>Users List</h1>
<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone No</th>
      <th>Role</th>
      <th>Created Event</th>
      
       </tr>
  </thead>
  <tbody>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_no %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user,class:"btn btn-primary" %></td>
    </tr>
  </br>
<% end %>
</tbody>
</table>

<%= link_to 'New User', new_user_registration_path,class:"btn btn-secondary" %>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Name : <%= @user.name %></br>
                 User Name : <%= @user.username %></br>
				 Phone No : <%= @user.phone_no %></br>
      Role : <%= @user.role %></h1></br>

<% @user_events.each do |event| %>
      Created Event Name : <h1> <%= event.event_name %></h1>
 <% end %>
    
</div></div></br>
<%= link_to 'Back', users_path,class:"btn btn-primary" %>